
APPS = ENV['APPS'].split(';')
HTTP_USER = ENV['HTTP_USER']
API_KEY = ENV['API_KEY']
NEWRELIC_API_ID= ENV['NEWRELIC_API_ID']
HEROKU_API_TOKEN = ENV['HEROKU_API_TOKEN']
REDIS_URI = ENV['REDIS_URI'] || ENV['REDISTOGO_URL'] || ENV['OPENREDIS_URL'] || 'redis://localhost:6379/'
DEPLOY_TTL = ENV['DEPLOY_TTL'] || 300
EMAIL_ENABLED = ENV['EMAIL_ENABLED'] == 'true'
ROLLBACK_ENABLED = ENV['ROLLBACK_ENABLED'] == 'true'

MAX_RETRIES = 5
LIMIT_ERRORS = 2
APPS_WAKEUP = 10


TEST_URIS = {
  'patata' => "http://www.google.es/"
}
